### ISSUE TITLE
Crear los distintos tipos de textBox con validaciones necesarios

### ISSUE THREAD

**Issue by RamiroV** [GastonTS/gdd-tp-2015#10]
- [x] Validación de campo obligatorio: que tenga algo dentro
- [x] Validación de campo numérico con coma: del tipo que tiene la tabla (18,2) si mi memoria no falla
- [x] Validación de campo sólo letras del alfabeto (a-Z)
- [x] Validación de campo telefónico
- [x] Validación de campo mail
- [x] Validación de campo DNI (que sean 7 u 8 números podría ser este)

**Comment by JuanFdS** [comment]
GG ez
