### ISSUE TITLE
Sacar cantidad_butacas en aeronave y mantener consistencia

### ISSUE THREAD

**Issue by JuanchiRios** [GastonTS/gdd-tp-2015#20]
Desnormalize la cantidad de butacas en la aeronave, hacete un trigger para que cada vez que se agregue una butaca me sumes 1 ahí.

**Comment by JuanchiRios** [comment]
@GastonTS no  te pongas a hacerlo antes de conversar con Juan

**Comment by GastonTS** [comment]
Quedamos en que esto no lo hacemos no? Cambio el titulo del issue para que sea sacar esto y que quede consistente.
