### ISSUE TITLE
Restar Millas

### ISSUE THREAD

**Issue by GastonTS** [GastonTS/gdd-tp-2015#3]
Se debe restar millas cuando
- [x] Cuando expira su duracion
- [x] Cuando se canjean por productos

**Comment by JuanchiRios** [comment]
Se supone que este trigger solo disminuye cierto? Las validaciones de que si se pueden canjear o no se hacen antes no?
Otra cosa el trigger de expiración pasado los 365 cuando se supone que debe activarse? Porque supongo que hay varias formas de hacerlo pero no sabría cual es la mejor
